spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?serverTimezone=UTC
    username: root
    password: leemer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 120.79.208.233
    port: 6379
  thymeleaf:
    cache: false
server:
  port: 8080
